title: Better Know a Framework
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
paginate: 25

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
